# Day 4 — Pandas Fundamentals

## Objective
Learn the fundamentals of Pandas for Data Analysis.

Topics:
- Series
- DataFrame
- DataFrame inspection
- Column selection
- Row selection
- Filtering
- Sorting
- Creating new columns
- Missing values
- Basic statistics

In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

## 1. Pandas Series

A Series is a one-dimensional labeled data structure.

In [3]:
sales = pd.Series([100, 200, 150, 300, 250])

sales

0    100
1    200
2    150
3    300
4    250
dtype: int64

In [4]:
print("First value:", sales[0])
print("Fourth value:", sales[3])

First value: 100
Fourth value: 300

## 2. Creating a DataFrame

A DataFrame is a two-dimensional table consisting of rows and columns.

In [5]:
data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [55000, 800, 1500, 12000],
    "Quantity": [2, 5, 3, 2]
}

df = pd.DataFrame(data)

df

    Product  Price  Quantity
0    Laptop  55000         2
1     Mouse    800         5
2  Keyboard   1500         3
3   Monitor  12000         2

## 3. Inspecting the DataFrame

In [6]:
print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

print("Shape:", df.shape)

print("Columns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

First 5 rows:

    Product  Price  Quantity
0    Laptop  55000         2
1     Mouse    800         5
2  Keyboard   1500         3
3   Monitor  12000         2

Last 5 rows:

    Product  Price  Quantity
0    Laptop  55000         2
1     Mouse    800         5
2  Keyboard   1500         3
3   Monitor  12000         2

Shape: (4, 3)
Columns:
Index(['Product', 'Price', 'Quantity'], dtype='object')

Data Types:
Product     object
Price        int64
Quantity     int64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   4 non-null      object
 1   Price     4 non-null      int64
 2   Quantity  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [8]:
df.describe()

              Price  Quantity
count      4.000000  4.000000
mean   17325.000000  3.000000
std    25633.750538  1.414214
min      800.000000  2.000000
25%     1325.000000  2.000000
50%     6750.000000  2.500000
75%    22750.000000  3.500000
max    55000.000000  5.000000

## 4. Selecting Columns

In [9]:
# Single column
df["Product"]

0      Laptop
1       Mouse
2    Keyboard
3     Monitor
Name: Product, dtype: object

In [10]:
# Multiple columns
df[["Product", "Price"]]

    Product  Price
0    Laptop  55000
1     Mouse    800
2  Keyboard   1500
3   Monitor  12000

## 5. Selecting Rows

### iloc
`iloc` selects rows and columns using integer positions.

### loc
`loc` selects data using labels or conditions.

In [11]:
# First row
df.iloc[0]

Product     Laptop
Price        55000
Quantity         2
Name: 0, dtype: object

In [12]:
# First two rows
df.iloc[0:2]

  Product  Price  Quantity
0  Laptop  55000         2
1   Mouse    800         5

In [13]:
# First row, second column
df.iloc[0, 1]

np.int64(55000)

In [14]:
# Select first row using label
df.loc[0]

Product     Laptop
Price        55000
Quantity         2
Name: 0, dtype: object

In [15]:
# Products with price greater than 5000
df.loc[df["Price"] > 5000]

   Product  Price  Quantity
0   Laptop  55000         2
3  Monitor  12000         2

## 6. Filtering Data

Filtering is one of the most important Pandas skills for Data Analysts.

In [16]:
# Quantity greater than 2
df[df["Quantity"] > 2]

    Product  Price  Quantity
1     Mouse    800         5
2  Keyboard   1500         3

In [17]:
# Price greater than 1000 AND quantity greater than 2
df[(df["Price"] > 1000) & (df["Quantity"] > 2)]

    Product  Price  Quantity
2  Keyboard   1500         3

In [18]:
# Price greater than 50000 OR quantity greater than 4
df[(df["Price"] > 50000) | (df["Quantity"] > 4)]

  Product  Price  Quantity
0  Laptop  55000         2
1   Mouse    800         5

### Logical Operators

- `&` → AND
- `|` → OR
- `~` → NOT

In [19]:
## 7. Sorting Data

In [20]:
# Sort by price - ascending
df.sort_values("Price")

    Product  Price  Quantity
1     Mouse    800         5
2  Keyboard   1500         3
3   Monitor  12000         2
0    Laptop  55000         2

In [21]:
# Sort by price - descending
df.sort_values("Price", ascending=False)

    Product  Price  Quantity
0    Laptop  55000         2
3   Monitor  12000         2
2  Keyboard   1500         3
1     Mouse    800         5

## 8. Creating a New Column

We can create a Sales column using:

Sales = Price × Quantity

In [22]:
df["Sales"] = df["Price"] * df["Quantity"]

df

    Product  Price  Quantity   Sales
0    Laptop  55000         2  110000
1     Mouse    800         5    4000
2  Keyboard   1500         3    4500
3   Monitor  12000         2   24000

In [23]:
## 9. Basic Statistics

In [24]:
print("Total Sales:", df["Sales"].sum())
print("Average Sales:", df["Sales"].mean())
print("Maximum Sales:", df["Sales"].max())
print("Minimum Sales:", df["Sales"].min())

Total Sales: 142500
Average Sales: 35625.0
Maximum Sales: 110000
Minimum Sales: 4000